---
title: "Tobacco Usage amoung Youth"
output: html_notebook
---

### Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
# Packages 

library(tidyverse)
library(haven)

```

### Data 

#### Data loading

```{r}
# Uses direct download links to download data 

# Due to varying url endings, 
# I used a function to automatically download data from the NYTS Website

Surveydatadownloader <-
  function(yearrange,urlending) 
    for (year in yearrange) {
      # Download zip file
      fullurl = paste("https://www.cdc.gov/tobacco/data_statistics/surveys/nyts/zip_files/"
                      ,year,"/",year,urlending,sep = "")
      download.file(fullurl,paste(year))
      # Unzip and put in data directory
      unzip(paste(year),exdir = "data",overwrite = TRUE)
      # Rename file to just year
      file.rename(paste("data/",list.files(path = "data", pattern = paste(year)), sep = ""),
                  paste("data/", year, sep = ""))
      # Remove previously downloaded zip file
      unlink(paste(year))
    }

# Download data from 2011 to 2020
Surveydatadownloader(2019:2020,"-nyts-dataset-and-codebook-sas.zip")
Surveydatadownloader(2018:2018, "-nyts-dataset-codebook-sas.zip")
Surveydatadownloader(c(2011,2014:2017),"-dataset-codebook-sas.zip")
Surveydatadownloader(2012:2013, "-codebook-dataset-sas.zip")

# Download data before 2011

for (year in c(1999,2000,2002,2004,2006,2009)) {
      # Download zip file
      fullurl = paste("https://www.cdc.gov/tobacco/data_statistics/surveys/nyts/zip_files/"
                      ,year,"_Codebook_Dataset_SAS.zip",sep = "")
      download.file(fullurl,paste(year))
      # Unzip and put in data directory
      if (year < 2006) 
      unzip(paste(year),exdir = paste("data/",year,sep = ""),overwrite = TRUE)
      else {
        unzip(paste(year),exdir = paste("data",sep = ""),overwrite = TRUE)
        file.rename(paste("data/",list.files(path = "data", pattern = paste(year)), sep = ""),
                  paste("data/", year, sep = ""))
      }
      # Remove previously downloaded zip file
      unlink(paste(year))
}




```

